name: luna_date
description: A simple lunar calendar app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^10.1.0
  intl: ^0.18.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  riverpod_lint:
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
