name: luna_date
description: A simple lunar calendar app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  awesome_extensions: ^2.0.9
  bot_toast: ^4.0.4
  calendar_date_picker2: ^0.5.2
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_bounceable: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.3.6
  form_field_validator: ^1.1.0
  go_router: ^9.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  lunar_calendar_converter_new: ^2.0.0
  modal_bottom_sheet: ^2.1.2
  riverpod_annotation: ^2.1.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  riverpod_lint:
  very_good_analysis: ^5.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700